app:
  name: usersvc
  port: 8000
database:
  name: usersvc 
  host: localhost
  port: 5432
  user: postgres 
  password: postgres 
  sslmode: disable 
saml:
  sp:
    root-url: "http://localhost:8000"
    certfile: saml-cert.pem
    keyfile: saml-key.pem
  idp:
    metadata-url: "http://localhost:8080/realms/master/protocol/saml/descriptor"